# Acquia alike stack
#
# - Apache 2.2
# - MySQL 5.6
# - PHP 5.6 / PHP 7.0
# - Varnish 3
# - Memcached 1.4
# - ApacheSolr 4.x

version: "2.1"

services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli

  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql

  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - PHP_IDE_CONFIG
      - SYMFONY_REQUIRE
    ports:
      - 9003
  # Varnish
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    depends_on:
      - web

#  # Memcached
#  memcached:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: memcached
#
#  # Solr
#  solr:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: solr

  # Browser
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    ports:
      - "${VNC_PORT_MAPPING:-5900}"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
