#!/usr/bin/env bash

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST, SITE_DIRECTORY.

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

cd $PROJECT_ROOT

# Start containers
fin up

# Remove old directories and install
rm -rf $PROJECT_ROOT/vendor
echo "Deleted: $PROJECT_ROOT/vendor"
rm -rf $DOCROOT_PATH/core
echo "Deleted: $DOCROOT_PATH/core"
rm -rf $DOCROOT_PATH/modules/contrib
echo "Deleted: $DOCROOT_PATH/modules/contrib"
fin exec composer install

# Set local config files
fin perm
cp $SITEDIR_PATH/default.settings.local.php $SITEDIR_PATH/settings.local.php
cp $SITEDIR_PATH/default.services.local.yml $SITEDIR_PATH/services.local.yml

# Set extra config
echo "
\$databases['default']['default'] = [
  'database' => 'default',
  'username' => 'user',
  'password' => 'user',
  'prefix' => '',
  'host' => 'db',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
];
" >> $SITEDIR_PATH/settings.local.php

# Set hosts
fin hosts remove $VIRTUAL_HOST
fin hosts add $VIRTUAL_HOST

# Set profile branch to match distro branch
DISTRO_BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
cd $DOCROOT_PATH/profiles/sitefarm/
git fetch origin
git fetch composer
if git checkout $DISTRO_BRANCH 2> /dev/null ; then
git pull origin $DISTRO_BRANCH
else
git checkout -b $DISTRO_BRANCH -t origin/$DISTRO_BRANCH
fi

# Install NVM to get a modern Node.js version
fin exec nvm install 10.16.3
# Set the node default version
fin exec nvm alias default 10.16.3

# Install Node packages and compile assets
fin theme-install

# Install site
cd $DOCROOT_PATH
fin drush site-install sitefarm -y --site-name="SiteFarm Acquia"

# Get login link
echo "Access SiteFarm: "
fin drush uli --uri="http://$VIRTUAL_HOST"

# Set permissions
fin perm
